command_timeout = 1000
[status]
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
disabled = false

[directory]
truncate_to_repo = false
